# -*- coding: utf-8 -*-
"""Assignment_Loops_Patterns.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CG8WFINr2P0He0txGNjN9Vvw2CtQOMco

#Task 1
 Abhay Aryan ,
 Referral ID-DIRSS3122
"""

for i in range(0,6):
  for j in range(i,6):
    print("*",end=" ")
  print()

for i in range(1,7):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

for i in range(0,5):
  for j in range(i,5):
    print(" ",end="")
  for j in range(i+1):
    print("*",end="")
  for j in range(i):
    print("*",end="")
  print()